name: Ruby Unit Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.7']

    steps:
    - uses: actions/checkout@v3
    - name: Install Depenencies
      run: sudo apt-get -y install raptor2-utils
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Start backend services via docker-compose
      run: docker compose up -d
    - name: Run tests
      run: bundle exec rake test


